# Generated by Django 6.0 on 2026-01-01 04:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='PH code must be in the format: XXX00', regex='^[A-Z]{3}\\d{2}$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/staff/')),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Matric number must be in the format: XX/00', regex='^[A-Z]{2}/\\d{2}$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/students/')),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('study_stream', models.CharField(choices=[('general', 'General'), ('mechatronics', 'Mechatronics'), ('ict', 'ICT'), ('biosciences', 'Biosciences')], max_length=20)),
                ('set_number', models.PositiveIntegerField()),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
