# Generated by Django 6.0 on 2026-01-05 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staffprofile_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='approval_status',
        ),
        migrations.CreateModel(
            name='RegistrationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_approval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
