# Generated by Django 6.0 on 2026-04-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='study_stream',
            field=models.CharField(choices=[('general', 'General'), ('ict', 'ICT'), ('mechatronics', 'Mechatronics'), ('pls', 'Physical and Life Sciences')], max_length=20),
        ),
    ]
