# Generated by Django 6.0 on 2026-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_studentprofile_study_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
