# Generated by Django 6.0 on 2026-06-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_classroommaterial_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroommaterial',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='classroom_materials/'),
        ),
    ]
