# Generated by Django 6.0 on 2026-07-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_course_streams_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='material_attachment',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
        migrations.AddField(
            model_name='course',
            name='set_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
