# Generated by Django 6.0 on 2026-07-04 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='classroommaterial',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'instructor']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroommaterial',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'instructor']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroommaterial',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_materials', to='core.course'),
        ),
    ]
