# Generated by Django 6.0 on 2026-07-04 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_assignment_published_course_set_course_stream_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroommaterial',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_materials', to='core.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroommaterial',
            name='instructor',
            field=models.ForeignKey(default=1, limit_choices_to={'role__in': ['teacher', 'instructor']}, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_materials', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        
    ]
