# Generated by Django 6.0 on 2026-07-04 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_content_scopes_cleanup'),
    ]

    operations = []
