# Generated by Django 6.0 on 2026-07-05 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_courseinstructor_state_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='set_number',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='stream',
        ),
        migrations.AddField(
            model_name='assignment',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classroommaterial',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_materials', to='core.course'),
        ),
        migrations.AlterField(
            model_name='classroommaterial',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'instructor']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
