# Generated by Django 6.0 on 2026-07-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_assignment_stream_set_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
