# Generated by Django 6.0 on 2026-07-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_enrollment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='set',
        ),
        migrations.RemoveField(
            model_name='course',
            name='stream',
        ),
    ]
