# Generated by Django 6.0 on 2026-07-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_course_legacy_set_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='published',
        ),
    ]
