from django.urls import path
from .views import (
    register_student,
    register_staff,
    login_user,
    protected_test,
    staff_only_view,
    me,
    list_notifications,
    mark_notification_read,
    list_pending_users,
    classroom_materials,
    classroom_material_detail,
    assignments,
    assignment_detail,
    submissions,
    save_submission_draft,
    approve_user,
    decline_user,
    list_all_users,
    list_active_interns,
    list_active_instructors,
    delete_user,
    upload_profile_photo,
    create_user,
    courses,
    course_detail,
    course_grades,
    instructor_dashboard,
    course_grade_detail,
    course_lessons,
    complete_lesson,
    student_dashboard,
    available_courses,
    my_courses,
    course_instructors,
    course_instructor_detail,
)

urlpatterns = [
    path("register/staff/", register_staff),
    path("register/student/", register_student),
    path("login/", login_user),
    path("test/protected/", protected_test),
    path("test/staff-only/", staff_only_view),
    path("auth/me", me),
    path("notifications/", list_notifications),
    path("classroom/materials/", classroom_materials),
    path("classroom/materials/<int:material_id>/", classroom_material_detail),
    path("assignments/", assignments),
    path("assignments/<int:assignment_id>/", assignment_detail),
    path("assignments/submissions/", submissions),
    path("assignments/submissions/draft/", save_submission_draft),
    path("notifications/<int:notification_id>/mark-read/", mark_notification_read),
    path("admin/pending-users/", list_pending_users),
    path("admin/users/", list_all_users),
    path("admin/users/create/", create_user),
    path("admin/users/<int:user_id>/", delete_user),
    path("admin/active-interns/", list_active_interns),
    path("admin/active-instructors/", list_active_instructors),
    path("admin/approve/<int:user_id>/", approve_user),
    path("admin/decline/<int:user_id>/", decline_user),
    path("admin/courses/", courses),
    path("admin/courses/<int:course_id>/", course_detail),
    path("admin/courses/<int:course_id>/grades/", course_grades),
    path("admin/courses/<int:course_id>/grades/<int:grade_id>/", course_grade_detail),
    path("admin/courses/<int:course_id>/instructors/", course_instructors),
    path("admin/courses/<int:course_id>/instructors/<int:instructor_id>/", course_instructor_detail),
    path("admin/courses/<int:course_id>/lessons/", course_lessons),
    path("admin/courses/<int:course_id>/lessons/<str:lesson_id>/complete/", complete_lesson),
    path("admin/dashboard/instructor/", instructor_dashboard),
    path("courses/<int:course_id>/", course_detail),
    path("courses/<int:course_id>/instructors/", course_instructors),
    path("courses/<int:course_id>/grades/", course_grades),
    path("dashboard/student/", student_dashboard),
    path("auth/profile/photo/", upload_profile_photo),
    path("intern/courses/available/", available_courses),
    path("courses/available/", available_courses),
    path("intern/my-courses/", my_courses),
    path("courses/my/", my_courses),
]
