# Generated by Django 6.0 on 2026-04-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='target_set',
            field=models.CharField(choices=[('1', 'Set 1'), ('2', 'Set 2'), ('3', 'Set 3'), ('4', 'Set 4'), ('5', 'Set 5')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
