# Generated by Django 6.0 on 2026-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_add_max_points_and_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(default='WRITTEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='max_points',
            field=models.IntegerField(default=100),
        ),
    ]
