# Generated by Django 6.0 on 2026-07-03 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_assessment_assessment_type_and_more'),
        ('core', '0025_courseinstructor_state_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'instructor']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
