# Generated by Django 6.0 on 2026-07-04 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_assessment_course_assessment_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'instructor']}, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
