# Generated by Django 6.0 on 2026-07-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_assessment_instructor'),
        ('core', '0025_courseinstructor_state_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='core.course'),
        ),
    ]
